name: thiocyanate
channels:
- ambermd
- omnia
- conda-forge
- defaults
dependencies:
- pytraj=2.0
- mdtraj=1.9
- pandas=0.22
- ipython=6.2
- jupyter=1.0
- matplotlib=2.1
- numpy=1.14
- scipy=1.0
- statsmodels=0.8
- openmm=7.1
- packmol=1
